### ISSUE TITLE
just downloaded KSPe and this pops up

### ISSUE THREAD

**Issue by GamerPlayz200** [net-lisias-ksp/KSPe#68]
idk what to do
![immagine_2024-03-01_144301097](https://github.com/net-lisias-ksp/KSPe/assets/133995712/9f7179cc-e045-4062-9fe5-15924f195b72)

**Comment by GamerPlayz200** [comment]
just checked,KSPe isnt even there wth?

**Comment by GamerPlayz200** [comment]
@Lisias

**Comment by GamerPlayz200** [comment]
Found out issue,Nevermind.

**Comment by GamerPlayz200** [comment]
(closed as not planned due to me having to manually delete the files since they arent compatible with my game or sum)

**Comment by Lisias** [comment]
@GamerPlayz200 , I need a good description of the problem otherwise I will not be able to understand what gone South and, so, will not be able to fix the problem.

Please describe

1. The environment you used to reproduce the problem (Operating System, CPU, GPU and Memory)
2. How did you installed the thing (and why).

Without these information, I don't know if it's something I did wrong, something I need to implement, or something you did wrong and I need to code a safety for it.

**Comment by Lisias** [comment]
Now I now what happened. User removed `000_KSPe` directory, but left the `00?_KSPe.dll` in `GameData`.

https://github.com/net-lisias-ksp/KSPe/issues/65 will have this tackled down.
